Fix typo.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6614,7 +6614,7 @@ EOF
 
     case "$host_os" in
     cygwin*)
-        echo "configure: warning: Using a cygwin build environment is unsupported. Configure cannot check for the presence of neceesary headers. Please upgrade to MozillaBuild; see http://developer.mozilla.org/en/docs/Windows_Build_Prerequisites" 1>&2
+        echo "configure: warning: Using a cygwin build environment is unsupported. Configure cannot check for the presence of necessary headers. Please upgrade to MozillaBuild; see http://developer.mozilla.org/en/docs/Windows_Build_Prerequisites" 1>&2
         ;;
 
     *)
